config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :events
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'welcome#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :meetings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:user_id, :description, :type_of_event)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id if current_user
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'El evento fue creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :title, :description, :start_time, :end_time, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @meetings = Meeting.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :type_of_event %>
    <%= form.text_field :type_of_event %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Description</th>
      <th>Type of event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.user_id %></td>
        <td><%= event.description %></td>
        <td><%= event.type_of_event %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @event.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Type of event:</strong>
  <%= @event.type_of_event %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>C</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render "partials/navigation" %>
      <p class="notice"><%= notice %></p>
      <%= yield %>
  </body>
</html>

app/views/meetings/_form.html.erb
<div class="mx-auto" style="width: 600px;">
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group paddin">
    <%= form.label :name, 'Titulo' %>
    <%= form.text_field :name, :class => "form-control" %>
  </div>


  <div class="form-group paddin">
    <%= form.label :description, 'Descripción' %>
    <%= form.text_area :description, :class => "form-control" %>
  </div>

  <div class="form-group paddin">
    <%= form.label :start_time, 'Inicio de evento' %>
    <%= form.datetime_select :start_time, { ampm: true, order: [:day, :month, :year] }, { class: "form-control1" } %>
  </div>

  <div class="form-group paddin">
    <%= form.label :end_time, 'Fin de evento' %>
    <%= form.datetime_select :end_time, { ampm: true, order: [:day, :month, :year] }, { class: "form-control1" } %>
  </div>

  <div class="actions btnpad2">
    <%= form.submit 'Crear evento',:class => "btn btn-success"%>
  </div>
<% end %>
</div>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.title %></td>
        <td><%= meeting.description %></td>
        <td><%= meeting.start_time %></td>
        <td><%= meeting.end_time %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @meeting.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meeting.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/partials/_navigation.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <p class="izq"></p>
    <%= link_to "Calendario", root_path, :class => "navbar-brand", :id => "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">Inicio<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">tareas pendientes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Quienes somos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contactenos</a>
        </li>
      </ul>
      <% if user_signed_in? %>
        <%= button_tag "Agregar Evento", :type => 'button', :class => "btn btn-outline-success my-2 my-sm-0", :onclick => "location.href = '#{new_user_registration_path}'" %>
        <p class="izq"></p>
        <%= button_tag "Cerrar Sesión", :type => 'button', method: :delete, :class => "btn btn-outline-success my-2 my-sm-0", :onclick => "location.href = '#{destroy_user_session_path}'"%>
      <% else %>
        <%= button_tag "Registrarse", :type => 'button', :class => "btn btn-outline-success my-2 my-sm-0", :onclick => "location.href = '#{new_user_registration_path}'" %>
        <p class="izq"></p>
        <%= button_tag "Iniciar Sesión", :type => 'button', :class => "btn btn-outline-success my-2 my-sm-0", :onclick => "location.href = '#{new_user_session_path}'" %>
        <p class="izq"></p>
      <% end %>
    </div>
  </nav>
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar1">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar1">
  <div class="calendar-heading">
    <%= link_to "<", calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to ">", calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>u
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  <h1>Bienvenido <% current_user.email %></h1>
  <%= month_calendar(events: @meetings) do |date, meetings| %>
    <%= date %>

    <% meetings.each do |meeting| %>
      <div class="border1">
        <%= meeting.name %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <section class="full-box section">
    <div class="container">
      <%= image_tag "prueba.jpg" , class: "imgfull" %>
      <div class="row">
        <div class="col-xs-12">
          <br>
          <h2 class="text-center text-titles">¡Bienvenido!</h2>
          <br>
          <p class="lead text-justify">
            ¡Hola!¿Tiene problemas para coordinar el desorden creativo de un equipo o para organizar el suyo? ¡Sabemos lo difícil que es! Nuestra solución es muy sencilla: programe, comparta y sincronice. El calendario de Calendario 24/7 le permite hacerlo todo en tan solo unos clics.
          </p>
        </div>
      </div>
      <br><br>
      <div class="row"  >
        <div class="col-xs-12 col-md-6" style="padding: 17px 0;">
          <i class="fa fa-briefcase icon-services" aria-hidden="true"></i>
          <h3 class="text-center text-titles">Nuestras Funciones</h3>
          <ul class="list-unstyled full-box list-services">
            <br>
            <li>
              <i class="fa fa-hand-o-right" aria-hidden="true"></i> &nbsp;
              • Calendarios grupales
            </li>
            <li>
              <i class="fa fa-hand-o-right" aria-hidden="true"></i> &nbsp;
              • Calendarios favoritos
            </li>
            <li>
              <i class="fa fa-hand-o-right" aria-hidden="true"></i> &nbsp;
              • Reuniones y sesiones informativas
            </li>
            <li>
              <i class="fa fa-hand-o-right" aria-hidden="true"></i> &nbsp;
              • Integración con CRM
            </li>
            <li>
              <i class="fa fa-hand-o-right" aria-hidden="true"></i> &nbsp;
              • Cuadro de ausencia
            </li>
            <li>
              <i class="fa fa-hand-o-right" aria-hidden="true"></i> &nbsp;
              • Programador de eventos
            </li>
          </ul>
        </div>
        <div class="col-xs-12 col-md-6" style="padding: 17px 0;">
          <i class="fa fa-heart icon-services" aria-hidden="true"></i>
          <h3 class="text-center text-titles">Imagenes del prototipo</h3>
          <br>
          <%= image_tag "prueba2.jpg" , class: "imgpe"%>
        </div>
    </div>
  </section>
  <section class="full-box cover section-lema">
    <div class="full-box section-lema-bg">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <p class="text-condensed text-center">
              «Necesita una herramienta competente que lo ayude a comunicarse con sus colegas, generar una lluvia de ideas para encontrar soluciones y gestionar proyectos. Todas estas tareas se pueden realizar utilizando un servicio llamado Calendario 24/7.»
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="full-box section section-a" style="background-color: #28a745;color: white" >
    <br>
    <h2 class="text-center text-titles">Beneficios de Calendario 24/7</h2>
    <br><br>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-pull-4 col-sm-4">
          <div class="section-a-container">

            <p>
              • Mantenga a todos los miembros del departamento sintonizados
            </p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-pull-4 col-sm-4">
          <div class="section-a-container">

            <p>
              • Nunca se pierda otra reunión ni se olvide de hacer una llamada de seguimiento
            </p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="section-a-container">

            <p>
              • Vea quien está planificando ausentarse y por cuanto tiempo
            </p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <div class="section-a-container">

            <p>
              • Comparta calendarios para coordinar entre los equipos y plataformas
            </p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="section-a-container">

            <p>
              • Programe eventos recurrentes y fije recordatorios
            </p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="section-a-container">

            <p>
              • Planifique, organice y registre reuniones, sesiones informativas y eventos
            </p>
          </div>
        </div>
      </div>
    </div>
    <br><br>
  </section>
  <section class="full-box section" style="background-color: #28a745;">
    <br>
    <h2 class="text-condensed text-center" style="color: #FFFFFF;">Todo lo que necesitas para realizar tareas, ahora en un solo lugar.</h2>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <p style="color:#fff;">
            • Las herramientas que más le gustan, perfectamente conectadas <br>
            Calendario 24/7, un lugar de trabajo integrado y fácil de usar, le permite dedicar menos tiempo a administrar sus tareas y más tiempo a hacerlas.
          </p>
        </div>
        <div class="col-xs-12 col-sm-4">
          <p style="color:#fff;">
            • Sugerencias inteligentes para ayudarlo a establecer prioridades<br>
            Haga lo importante y deje que Calendario 24/7 se encargue del resto con la mejor tecnología de IA y de búsqueda en su clase para trabajar de manera más inteligente.
          </p>
        </div>
        <div class="col-xs-12 col-sm-4">
          <p style="color:#fff;">
            • Soluciones flexibles para todas las empresas <br>
            Trabaje esté donde esté y con cualquier dispositivo, incluso sin conexión, con herramientas que lo ayudarán a integrar, personalizar y ampliar Google Workspace para satisfacer las necesidades particulares de su equipo.
          </p>
        </div>
      </div>
    </div>
  </section>
  <footer class="full-box footer">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <ul class="list-unstyled text-center social-icons">
            <li>
              <a href="#!">
                <i class="fa fa-facebook" aria-hidden="true" style="background-color: #2B3990;"></i>
              </a>
            </li>
            <li>
              <a href="#!">
                <i class="fa fa-twitter" aria-hidden="true" style="background-color: #26A9E0;"></i>
              </a>
            </li>
            <li>
              <a href="#!">
                <i class="fa fa-youtube" aria-hidden="true" style="background-color: #EC1B23"></i>
              </a>
            </li>
            <li>
              <a href="#!">
                <i class="fa fa-instagram" aria-hidden="true" style="background-color: #32689C"></i>
              </a>
            </li>
            <li>
              <a href="#!" aria-hidden="true" style="background-color: #BE1D2C"></i>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-xs-12">
          <p class="text-center text-condensed">
            Copyright &copy; 2020
          </p>
        </div>
      </div>
    </div>
  </footer>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/jquery-1.11.2.min.js"><\/script>')</script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/main.js"></script>

<% end %>